import { startOfWeek } from './date';
import type { AppState, Ingredient, MealPlan, Recipe } from './types';
import { DAY_KEYS } from './types';

const now = '2026-01-01T12:00:00.000Z';

function ingredient(
  id: string,
  name: string,
  quantity: number | null,
  unit: string,
  category: Ingredient['category'],
): Ingredient {
  return { id, name, quantity, unit, category };
}

export const SEED_RECIPES: Recipe[] = [
  {
    id: 'seed-salmon',
    name: 'Lemon salmon & new potatoes',
    description: 'A bright, dependable tray dinner with dill and greens.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['weeknight', 'quick', 'kid-friendly'],
    ingredients: [
      ingredient('salmon-1', 'salmon fillet', 600, 'g', 'protein'),
      ingredient('salmon-2', 'new potatoes', 800, 'g', 'produce'),
      ingredient('salmon-3', 'lemon', 1, '', 'produce'),
      ingredient('salmon-4', 'fresh dill', 1, 'bunch', 'produce'),
      ingredient('salmon-5', 'green beans', 300, 'g', 'produce'),
    ],
    notes: 'Serve the toddler portion before adding extra lemon.',
    favourite: true,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-pizza',
    name: 'Sourdough pizza night',
    description: 'A relaxed family ritual with flexible toppings.',
    servings: 4,
    prepMinutes: 25,
    cookMinutes: 15,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['winter', 'spring', 'summer', 'autumn'],
    tags: ['weekend', 'kid-friendly', 'favourite'],
    ingredients: [
      ingredient('pizza-1', 'pizza dough', 800, 'g', 'bakery'),
      ingredient('pizza-2', 'chopped tomatoes', 400, 'g', 'pantry'),
      ingredient('pizza-3', 'mozzarella', 300, 'g', 'dairy'),
      ingredient('pizza-4', 'mushrooms', 200, 'g', 'produce'),
      ingredient('pizza-5', 'olive oil', 2, 'tbsp', 'pantry'),
    ],
    notes: 'Make an extra dough ball for the freezer.',
    favourite: true,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-chicken',
    name: 'Roast chicken & roots',
    description: 'One-pan roast chicken that deliberately creates leftovers.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 70,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['autumn', 'winter'],
    tags: ['weekend', 'leftovers', 'kid-friendly'],
    ingredients: [
      ingredient('chicken-1', 'whole chicken', 1.6, 'kg', 'protein'),
      ingredient('chicken-2', 'carrots', 500, 'g', 'produce'),
      ingredient('chicken-3', 'potatoes', 800, 'g', 'produce'),
      ingredient('chicken-4', 'onion', 2, '', 'produce'),
      ingredient('chicken-5', 'chicken stock', 500, 'ml', 'pantry'),
    ],
    notes: 'Reserve leftover meat for tomorrow’s wraps.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-stirfry',
    name: 'Chicken & asparagus stir-fry',
    description: 'Fast, fresh and easy to separate into mild and grown-up portions.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['spring'],
    tags: ['weeknight', 'quick'],
    ingredients: [
      ingredient('stir-1', 'chicken breast', 600, 'g', 'protein'),
      ingredient('stir-2', 'asparagus', 350, 'g', 'produce'),
      ingredient('stir-3', 'rice', 300, 'g', 'pantry'),
      ingredient('stir-4', 'soy sauce', 3, 'tbsp', 'pantry'),
      ingredient('stir-5', 'fresh ginger', 25, 'g', 'produce'),
    ],
    notes: '',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-tacos',
    name: 'Fish tacos & lime slaw',
    description: 'Build-your-own tacos that work well for different appetites.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 15,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['weeknight', 'family-style'],
    ingredients: [
      ingredient('taco-1', 'white fish', 600, 'g', 'protein'),
      ingredient('taco-2', 'small tortillas', 12, '', 'bakery'),
      ingredient('taco-3', 'red cabbage', 0.5, 'head', 'produce'),
      ingredient('taco-4', 'lime', 2, '', 'produce'),
      ingredient('taco-5', 'sour cream', 200, 'ml', 'dairy'),
    ],
    notes: 'Keep chilli and raw onion as table toppings.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-chilli',
    name: 'Weeknight chilli',
    description: 'A freezer-friendly one-pot dinner with plenty of vegetables.',
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 40,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['autumn', 'winter'],
    tags: ['weeknight', 'batch-cook', 'freezer-friendly'],
    ingredients: [
      ingredient('chilli-1', 'minced beef', 700, 'g', 'protein'),
      ingredient('chilli-2', 'kidney beans', 2, 'tin', 'pantry'),
      ingredient('chilli-3', 'chopped tomatoes', 2, 'tin', 'pantry'),
      ingredient('chilli-4', 'bell pepper', 2, '', 'produce'),
      ingredient('chilli-5', 'onion', 2, '', 'produce'),
    ],
    notes: 'Freeze two portions before serving.',
    favourite: true,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-risotto',
    name: 'Mushroom & barley risotto',
    description: 'Earthy, comforting and less demanding than classic risotto.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 40,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['autumn', 'winter'],
    tags: ['weeknight', 'vegetarian', 'one-pot'],
    ingredients: [
      ingredient('risotto-1', 'mushrooms', 500, 'g', 'produce'),
      ingredient('risotto-2', 'pearl barley', 300, 'g', 'pantry'),
      ingredient('risotto-3', 'vegetable stock', 1, 'l', 'pantry'),
      ingredient('risotto-4', 'parmesan', 100, 'g', 'dairy'),
      ingredient('risotto-5', 'onion', 1, '', 'produce'),
    ],
    notes: '',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'seed-traybake',
    name: 'Sausage & root traybake',
    description: 'Minimal-prep comfort food for a busy evening.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 45,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['autumn', 'winter'],
    tags: ['weeknight', 'one-pan', 'kid-friendly'],
    ingredients: [
      ingredient('tray-1', 'sausages', 8, '', 'protein'),
      ingredient('tray-2', 'carrots', 400, 'g', 'produce'),
      ingredient('tray-3', 'parsnips', 300, 'g', 'produce'),
      ingredient('tray-4', 'potatoes', 600, 'g', 'produce'),
      ingredient('tray-5', 'red onion', 2, '', 'produce'),
    ],
    notes: '',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
];

/**
 * A one-time, additive catalogue expansion. These recipes are kept separate from the original
 * starter set so an existing household can receive them on schema migration without changing its
 * own recipes, plans, or later deletions.
 */
export const CATALOGUE_EXPANSION_RECIPES: Recipe[] = [
  {
    id: 'catalogue-chicken-curry-green-beans',
    name: 'Chicken curry with green beans',
    description: 'A gently spiced coconut-tomato curry with plenty of greens and brown rice.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['winter', 'autumn'],
    tags: ['weeknight', 'chicken', 'curry', 'green beans', 'wholegrain'],
    ingredients: [
      ingredient('curry-beans-1', 'chicken thigh fillets', 600, 'g', 'protein'),
      ingredient('curry-beans-2', 'green beans', 300, 'g', 'produce'),
      ingredient('curry-beans-3', 'onion', 1, '', 'produce'),
      ingredient('curry-beans-4', 'garlic', 3, 'cloves', 'produce'),
      ingredient('curry-beans-5', 'fresh ginger', 25, 'g', 'produce'),
      ingredient('curry-beans-6', 'curry powder', 2, 'tsp', 'pantry'),
      ingredient('curry-beans-7', 'chopped tomatoes', 400, 'g', 'pantry'),
      ingredient('curry-beans-8', 'light coconut milk', 400, 'ml', 'pantry'),
      ingredient('curry-beans-9', 'brown basmati rice', 300, 'g', 'pantry'),
    ],
    notes: 'Cook a mild base; add chilli at the table. It tastes even better the following day.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-chicken-udon-wok',
    name: 'Chicken wok with udon noodles',
    description: 'Fast chicken, colourful vegetables and chewy udon in a ginger-soy sauce.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 15,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['weeknight', 'quick', 'chicken', 'noodles', 'vegetable-forward'],
    ingredients: [
      ingredient('udon-1', 'chicken breast', 600, 'g', 'protein'),
      ingredient('udon-2', 'udon noodles', 600, 'g', 'pantry'),
      ingredient('udon-3', 'broccoli', 1, 'head', 'produce'),
      ingredient('udon-4', 'carrots', 2, '', 'produce'),
      ingredient('udon-5', 'red bell pepper', 1, '', 'produce'),
      ingredient('udon-6', 'edamame beans', 200, 'g', 'frozen'),
      ingredient('udon-7', 'fresh ginger', 25, 'g', 'produce'),
      ingredient('udon-8', 'garlic', 2, 'cloves', 'produce'),
      ingredient('udon-9', 'reduced-salt soy sauce', 4, 'tbsp', 'pantry'),
      ingredient('udon-10', 'sesame oil', 1, 'tbsp', 'pantry'),
    ],
    notes: 'Prep the vegetables in the morning to make this a true 15-minute dinner.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-indian-dahl',
    name: 'Indian red lentil dahl',
    description: 'A comforting tomato and red-lentil dahl with spinach and warming spices.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 30,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['winter', 'autumn'],
    tags: ['vegetarian', 'lentils', 'beans', 'one-pot', 'batch-cook'],
    ingredients: [
      ingredient('dahl-1', 'red lentils', 300, 'g', 'pantry'),
      ingredient('dahl-2', 'onion', 1, '', 'produce'),
      ingredient('dahl-3', 'garlic', 3, 'cloves', 'produce'),
      ingredient('dahl-4', 'fresh ginger', 25, 'g', 'produce'),
      ingredient('dahl-5', 'chopped tomatoes', 400, 'g', 'pantry'),
      ingredient('dahl-6', 'vegetable stock', 750, 'ml', 'pantry'),
      ingredient('dahl-7', 'baby spinach', 150, 'g', 'produce'),
      ingredient('dahl-8', 'garam masala', 2, 'tsp', 'pantry'),
      ingredient('dahl-9', 'brown basmati rice', 300, 'g', 'pantry'),
      ingredient('dahl-10', 'plain yoghurt', 200, 'g', 'dairy'),
    ],
    notes: 'Freeze two portions before serving. Stir in spinach just before eating.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-indian-chana-masala',
    name: 'Indian chana masala',
    description: 'Chickpeas simmered with tomatoes, spinach and fragrant Indian spices.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 30,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['winter', 'spring', 'autumn'],
    tags: ['vegetarian', 'chickpeas', 'beans', 'one-pot', 'make-ahead'],
    ingredients: [
      ingredient('chana-1', 'chickpeas', 2, 'tin', 'pantry'),
      ingredient('chana-2', 'onion', 1, '', 'produce'),
      ingredient('chana-3', 'garlic', 3, 'cloves', 'produce'),
      ingredient('chana-4', 'fresh ginger', 25, 'g', 'produce'),
      ingredient('chana-5', 'chopped tomatoes', 800, 'g', 'pantry'),
      ingredient('chana-6', 'baby spinach', 150, 'g', 'produce'),
      ingredient('chana-7', 'garam masala', 2, 'tsp', 'pantry'),
      ingredient('chana-8', 'ground cumin', 1, 'tsp', 'pantry'),
      ingredient('chana-9', 'brown basmati rice', 300, 'g', 'pantry'),
      ingredient('chana-10', 'lemon', 1, '', 'produce'),
    ],
    notes: 'Rinse canned chickpeas to reduce salt. Serve chilli separately for younger eaters.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-chicken-fajitas',
    name: 'Chicken fajitas with black beans',
    description: 'Build-your-own wholewheat fajitas with chicken, peppers, black beans and lime.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 15,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['weeknight', 'chicken', 'family-style', 'beans', 'wholegrain'],
    ingredients: [
      ingredient('fajitas-1', 'chicken breast', 600, 'g', 'protein'),
      ingredient('fajitas-2', 'wholewheat tortillas', 8, '', 'bakery'),
      ingredient('fajitas-3', 'bell peppers', 3, '', 'produce'),
      ingredient('fajitas-4', 'red onion', 1, '', 'produce'),
      ingredient('fajitas-5', 'black beans', 1, 'tin', 'pantry'),
      ingredient('fajitas-6', 'avocado', 2, '', 'produce'),
      ingredient('fajitas-7', 'lime', 2, '', 'produce'),
      ingredient('fajitas-8', 'plain yoghurt', 200, 'g', 'dairy'),
      ingredient('fajitas-9', 'fajita seasoning', 1, 'packet', 'pantry'),
    ],
    notes: 'Put beans, avocado, yoghurt and lime on the table so everyone can build their own.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-miso-salmon',
    name: 'Miso salmon bowls',
    description: 'Roasted salmon with miso, brown rice, broccoli, edamame and cucumber.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 20,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['weeknight', 'salmon', 'fish', 'wholegrain', 'bowl'],
    ingredients: [
      ingredient('miso-salmon-1', 'salmon fillet', 600, 'g', 'protein'),
      ingredient('miso-salmon-2', 'white miso paste', 2, 'tbsp', 'pantry'),
      ingredient('miso-salmon-3', 'brown rice', 300, 'g', 'pantry'),
      ingredient('miso-salmon-4', 'broccoli', 1, 'head', 'produce'),
      ingredient('miso-salmon-5', 'edamame beans', 200, 'g', 'frozen'),
      ingredient('miso-salmon-6', 'cucumber', 1, '', 'produce'),
      ingredient('miso-salmon-7', 'sesame seeds', 2, 'tbsp', 'pantry'),
      ingredient('miso-salmon-8', 'lime', 1, '', 'produce'),
    ],
    notes: 'Use reduced-salt miso if available; keep the glaze light and add extra lime at the table.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-lentil-sweet-potato-curry',
    name: 'Lentil, sweet potato & spinach curry',
    description: 'A vegetable-led red lentil curry with sweet potato, spinach and brown rice.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 35,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['winter', 'autumn'],
    tags: ['vegetarian', 'lentils', 'vegetable-forward', 'batch-cook', 'wholegrain'],
    ingredients: [
      ingredient('sweet-lentil-1', 'red lentils', 250, 'g', 'pantry'),
      ingredient('sweet-lentil-2', 'sweet potatoes', 700, 'g', 'produce'),
      ingredient('sweet-lentil-3', 'onion', 1, '', 'produce'),
      ingredient('sweet-lentil-4', 'chopped tomatoes', 400, 'g', 'pantry'),
      ingredient('sweet-lentil-5', 'vegetable stock', 700, 'ml', 'pantry'),
      ingredient('sweet-lentil-6', 'baby spinach', 150, 'g', 'produce'),
      ingredient('sweet-lentil-7', 'curry powder', 2, 'tsp', 'pantry'),
      ingredient('sweet-lentil-8', 'brown basmati rice', 300, 'g', 'pantry'),
    ],
    notes: 'A useful freezer meal; add a spoonful of yoghurt when serving if you like.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-tuna-pea-wholewheat-pasta',
    name: 'Tuna, tomato & pea wholewheat pasta',
    description: 'A fast pantry pasta with tuna, peas, tomatoes and spinach.',
    servings: 4,
    prepMinutes: 10,
    cookMinutes: 20,
    cookAttention: 'check-occasionally',
    makeAhead: 'none',
    seasons: ['spring', 'summer', 'autumn'],
    tags: ['weeknight', 'quick', 'fish', 'wholegrain', 'pantry'],
    ingredients: [
      ingredient('tuna-pasta-1', 'wholewheat pasta', 350, 'g', 'pantry'),
      ingredient('tuna-pasta-2', 'tuna in water', 3, 'tin', 'pantry'),
      ingredient('tuna-pasta-3', 'frozen peas', 300, 'g', 'frozen'),
      ingredient('tuna-pasta-4', 'cherry tomatoes', 300, 'g', 'produce'),
      ingredient('tuna-pasta-5', 'baby spinach', 100, 'g', 'produce'),
      ingredient('tuna-pasta-6', 'lemon', 1, '', 'produce'),
      ingredient('tuna-pasta-7', 'olive oil', 2, 'tbsp', 'pantry'),
      ingredient('tuna-pasta-8', 'parmesan', 60, 'g', 'dairy'),
    ],
    notes: 'Choose tuna in water and keep the pasta water to loosen the sauce.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-tofu-edamame-rice-bowls',
    name: 'Tofu & edamame rice bowls',
    description: 'Crisp tofu, edamame, colourful vegetables and brown rice with a sesame-lime dressing.',
    servings: 4,
    prepMinutes: 20,
    cookMinutes: 20,
    cookAttention: 'hands-on',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer'],
    tags: ['vegetarian', 'tofu', 'beans', 'wholegrain', 'vegetable-forward'],
    ingredients: [
      ingredient('tofu-bowl-1', 'firm tofu', 600, 'g', 'protein'),
      ingredient('tofu-bowl-2', 'brown rice', 300, 'g', 'pantry'),
      ingredient('tofu-bowl-3', 'edamame beans', 250, 'g', 'frozen'),
      ingredient('tofu-bowl-4', 'carrots', 2, '', 'produce'),
      ingredient('tofu-bowl-5', 'cucumber', 1, '', 'produce'),
      ingredient('tofu-bowl-6', 'red cabbage', 0.5, 'head', 'produce'),
      ingredient('tofu-bowl-7', 'reduced-salt soy sauce', 3, 'tbsp', 'pantry'),
      ingredient('tofu-bowl-8', 'sesame seeds', 2, 'tbsp', 'pantry'),
      ingredient('tofu-bowl-9', 'lime', 2, '', 'produce'),
    ],
    notes: 'Press the tofu and shred vegetables in advance. Add chilli crisp only at the table.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-cod-white-bean-tomato-bake',
    name: 'Cod, white bean & tomato bake',
    description: 'Cod baked over cannellini beans, tomatoes, spinach and lemon with wholegrain bread.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 25,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['winter', 'spring', 'autumn'],
    tags: ['fish', 'beans', 'one-pan', 'wholegrain', 'low attention'],
    ingredients: [
      ingredient('cod-bake-1', 'cod fillets', 600, 'g', 'protein'),
      ingredient('cod-bake-2', 'cannellini beans', 2, 'tin', 'pantry'),
      ingredient('cod-bake-3', 'cherry tomatoes', 400, 'g', 'produce'),
      ingredient('cod-bake-4', 'baby spinach', 150, 'g', 'produce'),
      ingredient('cod-bake-5', 'onion', 1, '', 'produce'),
      ingredient('cod-bake-6', 'lemon', 1, '', 'produce'),
      ingredient('cod-bake-7', 'olive oil', 2, 'tbsp', 'pantry'),
      ingredient('cod-bake-8', 'wholegrain bread', 1, 'loaf', 'bakery'),
    ],
    notes: 'Rinse canned beans and use lemon, garlic and herbs for flavour before reaching for salt.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-lentil-bolognese',
    name: 'Lentil bolognese with wholewheat spaghetti',
    description: 'A rich tomato, mushroom and lentil sauce for a familiar family pasta night.',
    servings: 6,
    prepMinutes: 15,
    cookMinutes: 40,
    cookAttention: 'check-occasionally',
    makeAhead: 'fully-ahead',
    seasons: ['winter', 'autumn'],
    tags: ['vegetarian', 'lentils', 'wholegrain', 'batch-cook', 'freezer-friendly'],
    ingredients: [
      ingredient('lentil-bolognese-1', 'green lentils', 250, 'g', 'pantry'),
      ingredient('lentil-bolognese-2', 'wholewheat spaghetti', 500, 'g', 'pantry'),
      ingredient('lentil-bolognese-3', 'mushrooms', 400, 'g', 'produce'),
      ingredient('lentil-bolognese-4', 'carrots', 2, '', 'produce'),
      ingredient('lentil-bolognese-5', 'celery', 2, 'stalks', 'produce'),
      ingredient('lentil-bolognese-6', 'onion', 1, '', 'produce'),
      ingredient('lentil-bolognese-7', 'chopped tomatoes', 800, 'g', 'pantry'),
      ingredient('lentil-bolognese-8', 'parmesan', 80, 'g', 'dairy'),
    ],
    notes: 'Freeze half the sauce separately; it also works in a baked pasta dish.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
  {
    id: 'catalogue-mediterranean-white-bean-traybake',
    name: 'Mediterranean white bean traybake',
    description: 'Roasted vegetables, white beans, feta and wholewheat couscous with lemon.',
    servings: 4,
    prepMinutes: 15,
    cookMinutes: 35,
    cookAttention: 'mostly-hands-off',
    makeAhead: 'prep-ahead',
    seasons: ['spring', 'summer', 'autumn'],
    tags: ['vegetarian', 'beans', 'one-pan', 'wholegrain', 'low attention'],
    ingredients: [
      ingredient('med-tray-1', 'cannellini beans', 2, 'tin', 'pantry'),
      ingredient('med-tray-2', 'courgettes', 2, '', 'produce'),
      ingredient('med-tray-3', 'bell peppers', 2, '', 'produce'),
      ingredient('med-tray-4', 'red onion', 1, '', 'produce'),
      ingredient('med-tray-5', 'cherry tomatoes', 300, 'g', 'produce'),
      ingredient('med-tray-6', 'feta', 150, 'g', 'dairy'),
      ingredient('med-tray-7', 'wholewheat couscous', 300, 'g', 'pantry'),
      ingredient('med-tray-8', 'lemon', 1, '', 'produce'),
      ingredient('med-tray-9', 'olive oil', 2, 'tbsp', 'pantry'),
    ],
    notes: 'Rinse the beans and add feta near the end so it stays in generous pieces.',
    favourite: false,
    lastCookedAt: null,
    timesCooked: 0,
    createdAt: now,
    updatedAt: now,
  },
];

export function createEmptyPlan(weekStart: string, servings: number): MealPlan {
  const slots = Object.fromEntries(
    DAY_KEYS.map((day) => [day, { recipeId: null, kind: 'recipe', locked: false, servings }]),
  ) as MealPlan['slots'];

  return {
    id: `plan-${weekStart}`,
    weekStart,
    slots,
    status: 'draft',
    updatedAt: new Date().toISOString(),
  };
}

export function createInitialState(): AppState {
  const currentWeek = startOfWeek();
  const defaultServings = 4;
  return {
    schemaVersion: 4,
    recipes: [...SEED_RECIPES, ...CATALOGUE_EXPANSION_RECIPES].map((recipe) => ({
      ...recipe,
      ingredients: recipe.ingredients.map((item) => ({ ...item })),
    })),
    plans: {
      [currentWeek]: createEmptyPlan(currentWeek, defaultServings),
    },
    shoppingLists: {},
    preferences: {
      householdName: 'The Family Table',
      defaultServings,
      theme: 'system',
      weatherLocation: null,
    },
  };
}
